[package]
name = "qdm"
version = "0.1.0"
edition = "2021"
description = "Quick Download Manager - Modern Open-Source Downloader in Rust & Iced"

[dependencies]
iced = { version = "0.13", features = ["tokio"] }
reqwest = "0.13.4"
dirs = "6.0"
sea-orm = { version = "2.0.0", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }