[package]
name = "qdm"
version = "0.1.0"
edition = "2021"
description = "Quick Download Manager - Modern Open-Source Downloader in Rust & Iced"

[dependencies]
iced = { version = "0.13", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
futures-util = { version = "0.3", default-features = false, features = ["std", "async-await"] }
reqwest = { version = "0.13.4", features = ["stream", "json"] }
dirs = "6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
thiserror = "2.0"